service: phase-1-with-error-functions
provider:
  name: aws
  runtime: python3.8
  region: ${opt:region, 'us-east-1'}
  memorySize: 128

functions:
  receive-message:
    name: receive-message
    handler: lambda.handler
    events:
      - sns: 
          arn: ${cf:phase-1-with-error.SNSErrorArn}