service: SQS-with-error
provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource:
        - ${cf:demo-database-dynamo.DynamoDBDemoArn}
    - Effect: 'Allow'
      Action:
        - 'sns:*'
      Resource:
        -  ${cf:phase-2-with-error.SNSAPIArn}
    - Effect: 'Allow'
      Action:
        - 'sqs:*'
      Resource:
        -  ${cf:phase-2-with-error.SQSQueueAPIArn}

functions:
  game-sell:
    handler: lambda.handler
    events:
      - http:
          path: /game-sell
          method: post
          cors: true
    environment:
      snsArn: ${cf:phase-2-with-error.SNSAPIArn}
  store-game-sell:
    handler: lambda.storeGameSell
    events:
      - sqs:
          arn: ${cf:phase-2-with-error.SQSQueueAPIArn}
          batchSize: 1
          enabled: true
    environment:
      dynamoTableName: ${cf:demo-database-dynamo.DynamoDBDemoNames}