service: phase-1-error-handling-functions
provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sqs:*'
      Resource:
        - ${cf:phase-1-error-handling.SQSQueueDLQSSMArnOutput}
    - Effect: 'Allow'
      Action:
        - 'sns:*'
      Resource:
        - ${cf:phase-1-error-handling.SNSErrorHandlingArn}

functions:
  receive-message:
    handler: lambda.handler
    events:
      - sns:
          arn: ${cf:phase-1-error-handling.SNSErrorHandlingArn}
    maximumRetryAttempts: 0
    onError: ${cf:phase-1-error-handling.SNSDLQHandlingArn}