service: sns-error-handling
provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sqs:*'
      Resource:
        - ${cf:phase-1-sns-error-handling.SQSQueueDLQSSMArnOutput}
    - Effect: 'Allow'
      Action:
        - 'sns:*'
      Resource:
        - ${cf:phase-1-sns-error-handling.SNSErrorHandlingArn}

functions:
  receive-message:
    name: receive-message
    handler: lambda.handler
    events:
      - sns:
          arn: ${cf:phase-1-sns-error-handling.SNSErrorHandlingArn}
    onError: ${cf:phase-1-sns-error-handling.SNSDLQHandlingArn}
    maximumRetryAttempts: 0
    destinations:
      onFailure: ${cf:phase-1-sns-error-handling.SNSDLQHandlingArn}