AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation SNS topic and SSM parameter sns-error-handling"
Resources:
  SNSError:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-sns"
  SNSErrorSSMArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /demo/sns/arn/error/handling
      Type: String
      Value: !Ref SNSError
  SNSErrorSSMName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /demo/sns/name/error/handling
      Type: String
      Value: !GetAtt SNSError.TopicName
  SNSDLQ:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "sns-error-dlq"
      Subscription:
        - Endpoint: !GetAtt 
            - SQSQueueDLQ
            - Arn
          Protocol: sqs
  SNSDLQSSMArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /demo/sns/dlq/arn/error/handling
      Type: String
      Value: !Ref SNSDLQ
  SQSQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-dlq-sns"
  SQSQueueDLQPolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - 'SQS:*'
            Resource: !GetAtt 'SQSQueueDLQ.Arn'
            Condition:
              ArnEquals:
                'aws:SourceArn': !Ref SNSDLQ
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - 'SQS:*'
            Resource: !GetAtt 'SQSQueueDLQ.Arn'
            Condition:
              ArnEquals:
                'aws:SourceArn': !Ref SNSError
      Queues:
        - !Ref SQSQueueDLQ
  SQSQueueDLQSSMURL:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /demo/sqs/url/sns/dlq
      Type: String
      Value: !Ref SQSQueueDLQ
  SQSQueueDLQSSMArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /demo/sqs/arn/sns/dlq
      Type: String
      Value: !GetAtt SQSQueueDLQ.Arn
  
Outputs:
  SNSErrorHandlingArn:
    Value: !Ref SNSError
    Export:
      Name: !Sub "${AWS::StackName}-SNSErrorHandlingArn"
  SNSDLQHandlingArn:
    Value: !Ref SNSDLQ
    Export:
      Name: !Sub "${AWS::StackName}-SNSDLQHandlingArn"
  SQSQueueDLQSSMURLOutput:
    Value: !Ref SQSQueueDLQ
    Export:
      Name: !Sub "${AWS::StackName}-SQSQueueDLQSSMURLOutput"
  SQSQueueDLQSSMArnOutput:
    Value: !GetAtt SQSQueueDLQ.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SQSQueueDLQSSMArnOutput"
  