AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation SNS topic and SSM parameter dynamo-error-handling"
Resources:
  SQSQueueDynamoDQL:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-sqs-dynamo-dlq"
      VisibilityTimeout: 10
      DelaySeconds: 15
  SNSDynamoDLQ:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-sns-dynamo-dlq"
      Subscription:
        - Endpoint: !GetAtt 
            - SQSQueueDynamoDQL
            - Arn
          Protocol: sqs
  SQSQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - 'SQS:*'
            Resource: !GetAtt 'SQSQueueDynamoDQL.Arn'
            Condition:
              ArnEquals:
                'aws:SourceArn': !Ref SNSDynamoDLQ
      Queues:
        - !Ref SQSQueueDynamoDQL

Outputs:
  SNSDynamoDLQArn:
    Value: !Ref SNSDynamoDLQ
    Export:
      Name: !Sub "${AWS::StackName}-SNSDynamoDLQArn"
  SQSQueueDynamoDQLUrl:
    Value: !Ref SQSQueueDynamoDQL
    Export:
      Name: !Sub "${AWS::StackName}-SQSQueueDynamoDQLUrl"
  SQSQueueDynamoDQLArn:
    Value: !GetAtt SQSQueueDynamoDQL.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SQSQueueDynamoDQLArn"